name: retro_cricket
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/btn1.png
    - assets/btn2.png
    - assets/btn3.png
    - assets/btn4.png
    - assets/btn5.png
    - assets/btn6.png
    - assets/batsman_end.png
    - assets/bowler_end.png
    - assets/batsman.png
    - assets/bowler.png
    - assets/bg.png
